[workspace]

[package]
name = "spike-t010"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", default-features = false, features = ["unstable-ext", "error-context", "std", "suggestions", "usage", "derive", "env", "string"] }
clap_complete = { version = "4.6.9", default-features = false, features = ["unstable-dynamic"] }
inquire = { version = "0.9.4", default-features = false, features = ["crossterm"] }
tokio = { version = "1.53.1", default-features = false, features = ["rt", "macros", "rt-multi-thread"] }
